enum textCodes {
  NOJWT = "No JWT provided",
  INVALIDJWT = "Provided JWT is Invalid",
  NOCARDSINFOLDER = "No cards found in this folder",
  CARDNOTINFOLDER = "Card not found in this folder",
  NOFOLDERFOUND = "No folder found",
  NOFOLDERSFOUND = "No folders found",
  NOACCESS = "No access",
  NOUSERFOUND = "No user found",
  NOCARDFOUND = "No card found",
  NOCARDSOVERVIEWFOUND = "No card overview found",
  NOCARDSFOUND = "No cards found",
  NOSCOREFOUND = "No score found",
  WRONGPASSWORD = "Wrong password",
  MISSINGDATA = "Missing data",
  INVALIDDATA = "Invalid data",
  USERMISSING = "User missing",
  DUPLICATE = "Duplicate entry",
  INVALIDEMAIL = "Email must be a valid email",
  FOLDERDELETED = "Folder deleted",
  CARDDELETED = "Card deleted",
  FOLDERUPDATED = "Folder updated",
  CARDUPDATED = "Card updated",
  CARDCREATED = "Card created",
  FOLDERCREATED = "Folder created",
  NODATA = "Request must contain at least one of [name, email, password]",
  SCORECREATED = "Score created",
  SCOREALREADYEXISTS = "Score entry already exists",
  SCOREUPDATED = "Score updated",
  SCOREDELETED = "Score deleted",
  EMAILALREADYEXISTS = "Email already exists",
  SHORTPASSWORD = "Password must be at least 8 characters long",
}

export = textCodes;
